config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

 resources :blog_posts do
   resource :cover_image, only: [:destroy], module: :blog_posts
 end


  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true

  # scope :sorted, -> { order("published_at desc NULLS LAST").order(updated_at: :desc)}
  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc)}
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge

    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image)) }
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
before_action :set_blog_post, only: %i[show edit update destroy]
before_action :authenticate_user!, except: %i[index show]
  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted

    @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
  end

  def show
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to blog_post_path(@blog_post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
   
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def update
   
    if @blog_post.update(blog_post_params)
      redirect_to blog_post_path(@blog_post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    
    @blog_post.destroy
    redirect_to root_path
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at, :cover_image)
  end

  def set_blog_post
    if user_signed_in?
      @blog_post = BlogPost.find(params[:id])
    else
      @blog_post = BlogPost.published.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%=  form_with model: blog_post do |f| %>
  <% if f.object.errors.any? %>
    <div>
      <% f.object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <p class="text-lg font-semibold mb-5">
    <%= f.label :title, "Titre" %><br>
    <%= f.text_field :title %>
  </p>


  <p class="text-lg font-semibold mb-5">
    <%= f.label :content, "Description" %><br>
    <%= f.rich_text_area :content %>
  </p>
  <p class="text-lg font-semibold mb-5">
    <%= f.label :cover_image, "Ajouter un fichier : " %>
    <% if blog_post.cover_image.present? %>
      <div id="<%= dom_id(blog_post, :cover_image)%>" class="mb-4">
        <%= image_tag blog_post.cover_image, alt: "text", class:"w-1/3"  %>
        <%= link_to "supprimer l'image", blog_post_cover_image_path(blog_post), data: {turbo_method: :delete, turbo_confirm: "Are u sure? any other changes will be lost"}, class:"underline p-4"  %>

      </div>
    <% end %>
    <%= f.file_field :cover_image %>
  </p>

  <p class="text-lg font-semibold mb-5">
    <%= f.label :published_at, "Date : " %>
    <%= f.datetime_select :published_at, include_blank: true %>
  </p>

  <p class="bg-primary text-white text-center p-4 rounded-lg w-1/3">
    <%= f.submit "Sauvegarder" %>
  </p>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="container mx-auto p-4 w-1/2">
  <h1 class="text-5xl font-bold text-primary mb-3">Editer l'article</h1>

  <%= render partial: 'form', locals: {blog_post: @blog_post} %>

  <%= button_to "Supprimer", @blog_post, method: :delete, data: {turbo_confirm: " R u sur ? "}, class:"btn btn-outline btn-error mt-4" %>

</div>

app/views/blog_posts/index.html.erb
<section class="container mx-auto p-4">
  <%= link_to "Se connecter", new_user_session_path, class:"btn btn-primary "  %>
  <h1 class="text-primary text-5xl font-extrabold text-center mb-6">Mes articles</h1>

  <div class="flex flex-wrap gap-4">
    <% @blog_posts.each do |blog_post| %>
      <div class="card bg-base-100 image-full w-96 shadow-xl opacity-85">

        <figure>
          <%= image_tag blog_post.cover_image,class:"w-[300px]", alt: "text" if blog_post.cover_image.attached? %>
        </figure>
        <div class="card-body">
          <h2><%= link_to blog_post.title, blog_post, class:"card-title" %></h2>
          <p><%= blog_post.content.to_plain_text.truncate(100) %></p>
          <p class="mt-2 italic"><%= blog_post.published_at != nil ? blog_post.published_at.strftime("%d-%m-%y à %H:%m") : "Non défini" %></p>
          <div class="card-actions  items-center justify-between">
            <div>
              <% if blog_post.draft? %>
                <div class="badge badge-neutral">Brouillon</div>
              <% elsif blog_post.scheduled? %>
                <div class="badge badge-primary">
                  <p class='text-red-400'>Programmé</p>
                </div>
              <% end %>
            </div>
            <%= link_to "Lire", blog_post, class:"btn btn-primary"  %>

          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="my-16 mx-auto">
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </div>

</section>

app/views/blog_posts/new.html.erb
<div class="container mx-auto p-4 w-1/2">
  <h1 class="text-primary text-5xl font-bold mb-7">Ajouter un article</h1>

  <%= render partial: "form", locals: {blog_post: @blog_post} %>

</div>

app/views/blog_posts/show.html.erb
<section class="container mx-auto p-4 flex flex-col items-center  mt-16">
  <%= image_tag @blog_post.cover_image,class:"w-[300px] mb-6", alt: "text" if @blog_post.cover_image.attached? %>
  <h1 class="text-5xl font-bold text-primary mb-6"><%= @blog_post.title %></h1>
  <p><%= @blog_post.content %></p>

  <%= link_to "Editer", edit_blog_post_path(@blog_post), class:"btn btn-outline mb-4"  %>

  <%= link_to "Retour", root_path, class:"btn btn-primary"  %>
</section>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="pastel">
  <head>
    <title><%= content_for(:title) || "Blog Tuto" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class=" mx-auto p-4 my-16">
    <div class="<%= 'hidden' unless notice.present? || alert.present? %>">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    </div>

    <div class="flex justify-end items-center gap-2">
      <% if user_signed_in? %>
        <%= link_to "Ajouter un article", new_blog_post_path, class:"btn btn-active btn-primary"  %>
        <%#= link_to "Profile", edit_user_session_path %>
        <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "btn btn-outline btn-secondary" %>
        <!--
      <%#%> else %>
      <%#= link_to "Sign up", new_user_registration_path %>
      <%#%> link_to "Login", new_user_session_path %>
      -->
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>